# Site settings
title: The Paper Trail
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A travelling Album by The Papers
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://the-paper-trail.com" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

collections:
  - cities
